version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_bookmarks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmarks_db
    ports:
      - "5432:5432"  # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
